apiVersion: v2
name: openfga
version: 0.1.0
appVersion: "v0.2.4"
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
description: OpenFGA is a high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar
engine: gotpl
home: https://github.com/AlexandreBrg/openfga-helm
keywords:
  - authorization
maitainers:
  - name: AlexandreBrg
    url: https://github.com/AlexandreBrg/openfga-helm