{{- if and (not .Values.externalDatabase.existingSecret) (eq .Values.persistencyMode "postgres") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-postgres" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: openfga
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  password: {{ include "common.secrets.passwords.manage" (dict "secret" (printf "%s-postgres" (include "common.names.fullname" .)) "key" "password" "length" 10 "providedValues" (list "externalDatabase.password") "context" $) }}
{{- end }}