name: Check for updates

on:
  push:

jobs:
  dependencies:
    name: Prepare Dependencies
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: Setup dependencies
        uses: ./.github/actions/setup

  openfga-update:
    runs-on: ubuntu-22.04
    needs:
      - dependencies
    steps:
      - uses: actions/checkout@v1
      - id: openfga
        name: "Get OpenFGA latest version"
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: openfga/openfga
          excludes: prerelease, draft
      - name: "Print result"
        run: |
          echo "tag_name: ${{ steps.openfga.outputs.release }}"
      - name: "Fetch current OpenFGA version"
        run: |
          echo "CURRENT_OPENFGA_VERSION=$(yq eval '.appVersion' openfga/Chart.yaml)" >> $GITHUB_ENV
          echo $(yq eval '.appVersion' openfga/Chart.yaml)