name: Check for updates

on:
  push:

jobs:
  dependencies:
    name: Prepare Dependencies
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: Setup dependencies
        uses: ./.github/actions/setup

  openfga-update:
    runs-on: ubuntu-22.04
    needs:
      - dependencies
    steps:
      - uses: actions/checkout@v1
      - name: "Get OpenFGA latest release"
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}
          exclude_types: "draft|prerelease"
          view_top: 1
      - name: "Print result"
        run: |
          echo "id: ${{ steps.last_release.outputs.id }}"
          echo "name: ${{ steps.last_release.outputs.name }}"
          echo "tag_name: ${{ steps.last_release.outputs.tag_name }}"
          echo "created_at: ${{ steps.last_release.outputs.created_atd }}"
          echo "draft: ${{ steps.last_release.outputs.draft }}"
          echo "prerelease: ${{ steps.last_release.outputs.prerelease }}"
      - name: "Fetch current OpenFGA version"
        run: |
          echo "CURRENT_OPENFGA_VERSION=$(yq eval '.appVersion' openfga/Chart.yaml)" >> $GITHUB_ENV
          echo $(yq eval '.appVersion' openfga/Chart.yaml)