name: Check for updates

on:
  push:

jobs:
  dependencies:
    name: Prepare Dependencies
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: Setup dependencies
        uses: ./.github/actions/setup

  openfga-update:
    runs-on: ubuntu-22.04
    needs:
      - dependencies
    steps:
      - uses: actions/checkout@v1
      - id: openfga
        name: "Get OpenFGA latest version"
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: openfga/openfga
          excludes: prerelease, draft
      - name: "Concatenate versions"
        run: |
          echo "latest version: ${{ steps.openfga.outputs.release }}"
          echo "LATEST_OPENFGA_VERSION=${{ steps.openfga.outputs.release }}" >> $GITHUB_ENV
          
          export CURRENT_VERSION=$(yq eval '.appVersion' openfga/Chart.yaml)
          echo "CURRENT_OPENFGA_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV
      
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/NEW_RELEASE_TEMPLATE.md
          update_existing: true
          search_existing: open